development:
  adapter: postgresql
  encoding: unicode
  database: todo-development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: remed-e-test1<%#= ENV['TEST_ENV_NUMBER'].to_i < 2 ? '1' : ENV['TEST_ENV_NUMBER'] %>
#   pool: 5
#   username: postgres
#   password: postgres
#   host: localhost
#   port: 5432
