# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c8b7d1b026bd14ddeac928b5642f13c602e0c5558cd39a8a1b8d1d5b687c5ddf2b4e202073cda2354c2365c7ecf39acce661dfb28a97597d70cbfb6df0a4567

test:
  secret_key_base: 3ecf8fa4edf7320d2f497fc06799e1f026dd2262899a0a5666b20f84aa0fba1f3ef0f9c0003cde53a43a6dc16536aa5e779a34becb6f16b6abf13c427df092c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
